n = 2998;
m = 3000;
Input_TempData = csvread('D:\White_paper\python\Input_data_9x9\Input_TempData.csv');
Temp1 = Input_TempData(1,n:m);
Temp2 = Input_TempData(2,n:m);
Temp3 = Input_TempData(3,n:m);
Temp4 = Input_TempData(4,n:m);
Temp5 = Input_TempData(5,n:m);
Temp6 = Input_TempData(6,n:m);
Temp7 = Input_TempData(7,n:m);
Temp8 = Input_TempData(8,n:m);
Temp9 = Input_TempData(9,n:m);
Temp10 = Input_TempData(10,n:m);
Temp11 = Input_TempData(11,n:m);
Temp12 = Input_TempData(12,n:m);
Temp13 = Input_TempData(13,n:m);
Temp14 = Input_TempData(14,n:m);
Temp15 = Input_TempData(15,n:m);
Temp16 = Input_TempData(16,n:m);
Temp17 = Input_TempData(17,n:m);
Temp18 = Input_TempData(18,n:m);
Temp19 = Input_TempData(19,n:m);
Temp20 = Input_TempData(20,n:m);
Temp21 = Input_TempData(21,n:m);
Temp22 = Input_TempData(22,n:m);
Temp23 = Input_TempData(23,n:m);
Temp24 = Input_TempData(24,n:m);
Temp25 = Input_TempData(25,n:m);
Temp26 = Input_TempData(26,n:m);
Temp27 = Input_TempData(27,n:m);
Temp28 = Input_TempData(28,n:m);
Temp29 = Input_TempData(29,n:m);
Temp30 = Input_TempData(30,n:m);
Temp31 = Input_TempData(31,n:m);
Temp32 = Input_TempData(32,n:m);
Temp33 = Input_TempData(33,n:m);
Temp34 = Input_TempData(34,n:m);
Temp35 = Input_TempData(35,n:m);
Temp36 = Input_TempData(36,n:m);
Temp37 = Input_TempData(37,n:m);
Temp38 = Input_TempData(38,n:m);
Temp39 = Input_TempData(39,n:m);
Temp40 = Input_TempData(40,n:m);
Temp41 = Input_TempData(41,n:m);
Temp42 = Input_TempData(42,n:m);
Temp43 = Input_TempData(43,n:m);
Temp44 = Input_TempData(44,n:m);
Temp45 = Input_TempData(45,n:m);
Temp46 = Input_TempData(46,n:m);
Temp47 = Input_TempData(47,n:m);
Temp48 = Input_TempData(48,n:m);
Temp49 = Input_TempData(49,n:m);
Temp50 = Input_TempData(50,n:m);
Temp51 = Input_TempData(51,n:m);
Temp52 = Input_TempData(52,n:m);
Temp53 = Input_TempData(53,n:m);
Temp54 = Input_TempData(54,n:m);
Temp55 = Input_TempData(55,n:m);
Temp56 = Input_TempData(56,n:m);
Temp57 = Input_TempData(57,n:m);
Temp58 = Input_TempData(58,n:m);
Temp59 = Input_TempData(59,n:m);
Temp60 = Input_TempData(60,n:m);
Temp61 = Input_TempData(61,n:m);
Temp62 = Input_TempData(62,n:m);
Temp63 = Input_TempData(63,n:m);
Temp64 = Input_TempData(64,n:m);
Temp65 = Input_TempData(65,n:m);
Temp66 = Input_TempData(66,n:m);
Temp67 = Input_TempData(67,n:m);
Temp68 = Input_TempData(68,n:m);
Temp69 = Input_TempData(69,n:m);
Temp70 = Input_TempData(70,n:m);
Temp71 = Input_TempData(71,n:m);
Temp72 = Input_TempData(72,n:m);
Temp73 = Input_TempData(73,n:m);
Temp74 = Input_TempData(74,n:m);
Temp75 = Input_TempData(75,n:m);
Temp76 = Input_TempData(76,n:m);
Temp77 = Input_TempData(77,n:m);
Temp78 = Input_TempData(78,n:m);
Temp79 = Input_TempData(79,n:m);
Temp80 = Input_TempData(80,n:m);
Temp81 = Input_TempData(81,n:m);
Temp82 = Input_TempData(82,n:m);
Temp83 = Input_TempData(83,n:m);
Temp84 = Input_TempData(84,n:m);
Temp85 = Input_TempData(85,n:m);
Temp86 = Input_TempData(86,n:m);
Temp87 = Input_TempData(87,n:m);
Temp88 = Input_TempData(88,n:m);
Temp89 = Input_TempData(89,n:m);
Temp90 = Input_TempData(90,n:m);
Temp91 = Input_TempData(91,n:m);
Temp92 = Input_TempData(92,n:m);
Temp93 = Input_TempData(93,n:m);
Temp94 = Input_TempData(94,n:m);
Temp95 = Input_TempData(95,n:m);
Temp96 = Input_TempData(96,n:m);
Temp97 = Input_TempData(97,n:m);
Temp98 = Input_TempData(98,n:m);
Temp99 = Input_TempData(99,n:m);
Temp100 = Input_TempData(100,n:m);
Temp101 = Input_TempData(101,n:m);
Temp102 = Input_TempData(102,n:m);
Temp103 = Input_TempData(103,n:m);
Temp104 = Input_TempData(104,n:m);
Temp105 = Input_TempData(105,n:m);
Temp106 = Input_TempData(106,n:m);
Temp107 = Input_TempData(107,n:m);
Temp108 = Input_TempData(108,n:m);
Temp109 = Input_TempData(109,n:m);
Temp110 = Input_TempData(110,n:m);
Temp111 = Input_TempData(111,n:m);
Temp112 = Input_TempData(112,n:m);
Temp113 = Input_TempData(113,n:m);
Temp114 = Input_TempData(114,n:m);
Temp115 = Input_TempData(115,n:m);
Temp116 = Input_TempData(116,n:m);
Temp117 = Input_TempData(117,n:m);
Temp118 = Input_TempData(118,n:m);
Temp119 = Input_TempData(119,n:m);
Temp120 = Input_TempData(120,n:m);
Temp121 = Input_TempData(121,n:m);
Temp122 = Input_TempData(122,n:m);
Temp123 = Input_TempData(123,n:m);
Temp124 = Input_TempData(124,n:m);
Temp125 = Input_TempData(125,n:m);
Temp126 = Input_TempData(126,n:m);
Temp127 = Input_TempData(127,n:m);
Temp128 = Input_TempData(128,n:m);
Temp129 = Input_TempData(129,n:m);
Temp130 = Input_TempData(130,n:m);
Temp131 = Input_TempData(131,n:m);
Temp132 = Input_TempData(132,n:m);
Temp133 = Input_TempData(133,n:m);
Temp134 = Input_TempData(134,n:m);
Temp135 = Input_TempData(135,n:m);
Temp136 = Input_TempData(136,n:m);
Temp137 = Input_TempData(137,n:m);
Temp138 = Input_TempData(138,n:m);
Temp139 = Input_TempData(139,n:m);
Temp140 = Input_TempData(140,n:m);
Temp141 = Input_TempData(141,n:m);
Temp142 = Input_TempData(142,n:m);
Temp143 = Input_TempData(143,n:m);
Temp144 = Input_TempData(144,n:m);
Temp145 = Input_TempData(145,n:m);
Temp146 = Input_TempData(146,n:m);
Temp147 = Input_TempData(147,n:m);
Temp148 = Input_TempData(148,n:m);
Temp149 = Input_TempData(149,n:m);
Temp150 = Input_TempData(150,n:m);
Temp151 = Input_TempData(151,n:m);
Temp152 = Input_TempData(152,n:m);
Temp153 = Input_TempData(153,n:m);
Temp154 = Input_TempData(154,n:m);
Temp155 = Input_TempData(155,n:m);
Temp156 = Input_TempData(156,n:m);
Temp157 = Input_TempData(157,n:m);
Temp158 = Input_TempData(158,n:m);
Temp159 = Input_TempData(159,n:m);
Temp160 = Input_TempData(160,n:m);
Temp161 = Input_TempData(161,n:m);
Temp162 = Input_TempData(162,n:m);

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('D:\White_paper');

model.label('tomographic_thermal_new.mph');

model.param.set('StandardTemp', '293.15');

model.component.create('comp1', true);

model.component('comp1').geom.create('geom1', 3);

model.result.table.create('tbl1', 'Table');

model.component('comp1').mesh.create('mesh1');

model.component('comp1').geom('geom1').create('imp1', 'Import');
model.component('comp1').geom('geom1').feature('imp1').set('type', 'cad');
model.component('comp1').geom('geom1').feature('imp1').set('filename', 'D:\White_paper\new_mechanism.SLDASM');
model.component('comp1').geom('geom1').run;

model.view.create('view2', 2);

model.component('comp1').material.create('mat1', 'Common');
model.component('comp1').material.create('mat2', 'Common');
model.component('comp1').material('mat2').selection.set([1]);

model.component('comp1').physics.create('ht', 'HeatTransfer', 'geom1');
model.component('comp1').physics('ht').create('temp1', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp1').selection.set([93]);
model.component('comp1').physics('ht').create('temp2', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp2').selection.set([201]);
model.component('comp1').physics('ht').create('temp3', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp3').selection.set([309]);
model.component('comp1').physics('ht').create('temp4', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp4').selection.set([417]);
model.component('comp1').physics('ht').create('temp5', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp5').selection.set([525]);
model.component('comp1').physics('ht').create('temp6', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp6').selection.set([633]);
model.component('comp1').physics('ht').create('temp7', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp7').selection.set([741]);
model.component('comp1').physics('ht').create('temp8', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp8').selection.set([849]);
model.component('comp1').physics('ht').create('temp9', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp9').selection.set([957]);
model.component('comp1').physics('ht').create('temp10', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp10').selection.set([83]);
model.component('comp1').physics('ht').create('temp11', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp11').selection.set([191]);
model.component('comp1').physics('ht').create('temp12', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp12').selection.set([299]);
model.component('comp1').physics('ht').create('temp13', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp13').selection.set([407]);
model.component('comp1').physics('ht').create('temp14', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp14').selection.set([515]);
model.component('comp1').physics('ht').create('temp15', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp15').selection.set([623]);
model.component('comp1').physics('ht').create('temp16', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp16').selection.set([731]);
model.component('comp1').physics('ht').create('temp17', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp17').selection.set([839]);
model.component('comp1').physics('ht').create('temp18', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp18').selection.set([947]);
model.component('comp1').physics('ht').create('temp19', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp19').selection.set([73]);
model.component('comp1').physics('ht').create('temp20', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp20').selection.set([181]);
model.component('comp1').physics('ht').create('temp21', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp21').selection.set([289]);
model.component('comp1').physics('ht').create('temp22', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp22').selection.set([397]);
model.component('comp1').physics('ht').create('temp23', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp23').selection.set([505]);
model.component('comp1').physics('ht').create('temp24', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp24').selection.set([613]);
model.component('comp1').physics('ht').create('temp25', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp25').selection.set([721]);
model.component('comp1').physics('ht').create('temp26', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp26').selection.set([829]);
model.component('comp1').physics('ht').create('temp27', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp27').selection.set([937]);
model.component('comp1').physics('ht').create('temp28', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp28').selection.set([63]);
model.component('comp1').physics('ht').create('temp29', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp29').selection.set([171]);
model.component('comp1').physics('ht').create('temp30', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp30').selection.set([279]);
model.component('comp1').physics('ht').create('temp31', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp31').selection.set([387]);
model.component('comp1').physics('ht').create('temp32', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp32').selection.set([495]);
model.component('comp1').physics('ht').create('temp33', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp33').selection.set([603]);
model.component('comp1').physics('ht').create('temp34', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp34').selection.set([711]);
model.component('comp1').physics('ht').create('temp35', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp35').selection.set([819]);
model.component('comp1').physics('ht').create('temp36', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp36').selection.set([927]);
model.component('comp1').physics('ht').create('temp37', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp37').selection.set([53]);
model.component('comp1').physics('ht').create('temp38', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp38').selection.set([161]);
model.component('comp1').physics('ht').create('temp39', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp39').selection.set([269]);
model.component('comp1').physics('ht').create('temp40', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp40').selection.set([377]);
model.component('comp1').physics('ht').create('temp41', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp41').selection.set([485]);
model.component('comp1').physics('ht').create('temp42', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp42').selection.set([593]);
model.component('comp1').physics('ht').create('temp43', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp43').selection.set([701]);
model.component('comp1').physics('ht').create('temp44', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp44').selection.set([809]);
model.component('comp1').physics('ht').create('temp45', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp45').selection.set([917]);
model.component('comp1').physics('ht').create('temp46', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp46').selection.set([43]);
model.component('comp1').physics('ht').create('temp47', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp47').selection.set([151]);
model.component('comp1').physics('ht').create('temp48', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp48').selection.set([259]);
model.component('comp1').physics('ht').create('temp49', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp49').selection.set([367]);
model.component('comp1').physics('ht').create('temp50', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp50').selection.set([475]);
model.component('comp1').physics('ht').create('temp51', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp51').selection.set([583]);
model.component('comp1').physics('ht').create('temp52', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp52').selection.set([691]);
model.component('comp1').physics('ht').create('temp53', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp53').selection.set([799]);
model.component('comp1').physics('ht').create('temp54', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp54').selection.set([907]);
model.component('comp1').physics('ht').create('temp55', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp55').selection.set([33]);
model.component('comp1').physics('ht').create('temp56', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp56').selection.set([141]);
model.component('comp1').physics('ht').create('temp57', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp57').selection.set([249]);
model.component('comp1').physics('ht').create('temp58', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp58').selection.set([357]);
model.component('comp1').physics('ht').create('temp59', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp59').selection.set([465]);
model.component('comp1').physics('ht').create('temp60', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp60').selection.set([573]);
model.component('comp1').physics('ht').create('temp61', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp61').selection.set([681]);
model.component('comp1').physics('ht').create('temp62', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp62').selection.set([789]);
model.component('comp1').physics('ht').create('temp63', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp63').selection.set([897]);
model.component('comp1').physics('ht').create('temp64', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp64').selection.set([23]);
model.component('comp1').physics('ht').create('temp65', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp65').selection.set([131]);
model.component('comp1').physics('ht').create('temp66', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp66').selection.set([239]);
model.component('comp1').physics('ht').create('temp67', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp67').selection.set([347]);
model.component('comp1').physics('ht').create('temp68', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp68').selection.set([455]);
model.component('comp1').physics('ht').create('temp69', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp69').selection.set([563]);
model.component('comp1').physics('ht').create('temp70', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp70').selection.set([671]);
model.component('comp1').physics('ht').create('temp71', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp71').selection.set([779]);
model.component('comp1').physics('ht').create('temp72', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp72').selection.set([887]);
model.component('comp1').physics('ht').create('temp73', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp73').selection.set([13]);
model.component('comp1').physics('ht').create('temp74', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp74').selection.set([121]);
model.component('comp1').physics('ht').create('temp75', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp75').selection.set([229]);
model.component('comp1').physics('ht').create('temp76', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp76').selection.set([337]);
model.component('comp1').physics('ht').create('temp77', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp77').selection.set([445]);
model.component('comp1').physics('ht').create('temp78', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp78').selection.set([553]);
model.component('comp1').physics('ht').create('temp79', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp79').selection.set([661]);
model.component('comp1').physics('ht').create('temp80', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp80').selection.set([769]);
model.component('comp1').physics('ht').create('temp81', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp81').selection.set([877]);
model.component('comp1').physics('ht').create('temp82', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp82').selection.set([88]);
model.component('comp1').physics('ht').create('temp83', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp83').selection.set([196]);
model.component('comp1').physics('ht').create('temp84', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp84').selection.set([304]);
model.component('comp1').physics('ht').create('temp85', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp85').selection.set([412]);
model.component('comp1').physics('ht').create('temp86', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp86').selection.set([520]);
model.component('comp1').physics('ht').create('temp87', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp87').selection.set([628]);
model.component('comp1').physics('ht').create('temp88', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp88').selection.set([736]);
model.component('comp1').physics('ht').create('temp89', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp89').selection.set([844]);
model.component('comp1').physics('ht').create('temp90', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp90').selection.set([952]);
model.component('comp1').physics('ht').create('temp91', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp91').selection.set([78]);
model.component('comp1').physics('ht').create('temp92', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp92').selection.set([186]);
model.component('comp1').physics('ht').create('temp93', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp93').selection.set([294]);
model.component('comp1').physics('ht').create('temp94', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp94').selection.set([402]);
model.component('comp1').physics('ht').create('temp95', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp95').selection.set([510]);
model.component('comp1').physics('ht').create('temp96', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp96').selection.set([618]);
model.component('comp1').physics('ht').create('temp97', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp97').selection.set([726]);
model.component('comp1').physics('ht').create('temp98', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp98').selection.set([834]);
model.component('comp1').physics('ht').create('temp99', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp99').selection.set([942]);
model.component('comp1').physics('ht').create('temp100', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp100').selection.set([68]);
model.component('comp1').physics('ht').create('temp101', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp101').selection.set([176]);
model.component('comp1').physics('ht').create('temp102', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp102').selection.set([284]);
model.component('comp1').physics('ht').create('temp103', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp103').selection.set([392]);
model.component('comp1').physics('ht').create('temp104', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp104').selection.set([500]);
model.component('comp1').physics('ht').create('temp105', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp105').selection.set([608]);
model.component('comp1').physics('ht').create('temp106', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp106').selection.set([716]);
model.component('comp1').physics('ht').create('temp107', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp107').selection.set([824]);
model.component('comp1').physics('ht').create('temp108', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp108').selection.set([932]);
model.component('comp1').physics('ht').create('temp109', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp109').selection.set([58]);
model.component('comp1').physics('ht').create('temp110', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp110').selection.set([166]);
model.component('comp1').physics('ht').create('temp111', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp111').selection.set([274]);
model.component('comp1').physics('ht').create('temp112', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp112').selection.set([382]);
model.component('comp1').physics('ht').create('temp113', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp113').selection.set([490]);
model.component('comp1').physics('ht').create('temp114', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp114').selection.set([598]);
model.component('comp1').physics('ht').create('temp115', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp115').selection.set([706]);
model.component('comp1').physics('ht').create('temp116', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp116').selection.set([814]);
model.component('comp1').physics('ht').create('temp117', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp117').selection.set([922]);
model.component('comp1').physics('ht').create('temp118', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp118').selection.set([48]);
model.component('comp1').physics('ht').create('temp119', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp119').selection.set([156]);
model.component('comp1').physics('ht').create('temp120', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp120').selection.set([264]);
model.component('comp1').physics('ht').create('temp121', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp121').selection.set([372]);
model.component('comp1').physics('ht').create('temp122', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp122').selection.set([480]);
model.component('comp1').physics('ht').create('temp123', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp123').selection.set([588]);
model.component('comp1').physics('ht').create('temp124', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp124').selection.set([696]);
model.component('comp1').physics('ht').create('temp125', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp125').selection.set([804]);
model.component('comp1').physics('ht').create('temp126', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp126').selection.set([912]);
model.component('comp1').physics('ht').create('temp127', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp127').selection.set([38]);
model.component('comp1').physics('ht').create('temp128', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp128').selection.set([146]);
model.component('comp1').physics('ht').create('temp129', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp129').selection.set([254]);
model.component('comp1').physics('ht').create('temp130', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp130').selection.set([362]);
model.component('comp1').physics('ht').create('temp131', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp131').selection.set([470]);
model.component('comp1').physics('ht').create('temp132', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp132').selection.set([578]);
model.component('comp1').physics('ht').create('temp133', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp133').selection.set([686]);
model.component('comp1').physics('ht').create('temp134', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp134').selection.set([794]);
model.component('comp1').physics('ht').create('temp135', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp135').selection.set([902]);
model.component('comp1').physics('ht').create('temp136', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp136').selection.set([28]);
model.component('comp1').physics('ht').create('temp137', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp137').selection.set([136]);
model.component('comp1').physics('ht').create('temp138', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp138').selection.set([244]);
model.component('comp1').physics('ht').create('temp139', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp139').selection.set([352]);
model.component('comp1').physics('ht').create('temp140', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp140').selection.set([460]);
model.component('comp1').physics('ht').create('temp141', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp141').selection.set([568]);
model.component('comp1').physics('ht').create('temp142', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp142').selection.set([676]);
model.component('comp1').physics('ht').create('temp143', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp143').selection.set([784]);
model.component('comp1').physics('ht').create('temp144', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp144').selection.set([892]);
model.component('comp1').physics('ht').create('temp145', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp145').selection.set([18]);
model.component('comp1').physics('ht').create('temp146', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp146').selection.set([126]);
model.component('comp1').physics('ht').create('temp147', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp147').selection.set([234]);
model.component('comp1').physics('ht').create('temp148', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp148').selection.set([342]);
model.component('comp1').physics('ht').create('temp149', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp149').selection.set([450]);
model.component('comp1').physics('ht').create('temp150', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp150').selection.set([558]);
model.component('comp1').physics('ht').create('temp151', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp151').selection.set([666]);
model.component('comp1').physics('ht').create('temp152', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp152').selection.set([774]);
model.component('comp1').physics('ht').create('temp153', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp153').selection.set([882]);
model.component('comp1').physics('ht').create('temp154', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp154').selection.set([8]);
model.component('comp1').physics('ht').create('temp155', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp155').selection.set([116]);
model.component('comp1').physics('ht').create('temp156', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp156').selection.set([224]);
model.component('comp1').physics('ht').create('temp157', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp157').selection.set([332]);
model.component('comp1').physics('ht').create('temp158', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp158').selection.set([440]);
model.component('comp1').physics('ht').create('temp159', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp159').selection.set([548]);
model.component('comp1').physics('ht').create('temp160', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp160').selection.set([656]);
model.component('comp1').physics('ht').create('temp161', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp161').selection.set([764]);
model.component('comp1').physics('ht').create('temp162', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp162').selection.set([872]);
model.component('comp1').physics.create('solid', 'SolidMechanics', 'geom1');
model.component('comp1').physics('solid').create('fix1', 'Fixed', 1);
model.component('comp1').physics('solid').feature('fix1').selection.set([1 6 1953 1956]);

model.component('comp1').multiphysics.create('te1', 'ThermalExpansion', 3);
model.component('comp1').multiphysics('te1').selection.all;
model.component('comp1').multiphysics.create('tc1', 'TemperatureCoupling', -1);

model.view('view2').axis.set('xmin', 0.8499999046325684);
model.view('view2').axis.set('xmax', 4.150000095367432);
model.view('view2').axis.set('ymin', -6.650005340576172);
model.view('view2').axis.set('ymax', 107.6500015258789);
model.view('view2').axis.set('viewscaletype', 'automatic');

model.component('comp1').material('mat1').propertyGroup('def').set('thermalconductivity', {'0.21' '0' '0' '0' '0.21' '0' '0' '0' '0.21'});
model.component('comp1').material('mat1').propertyGroup('def').set('density', '1125');
model.component('comp1').material('mat1').propertyGroup('def').set('heatcapacity', '4200');
model.component('comp1').material('mat1').propertyGroup('def').set('youngsmodulus', '80e6');
model.component('comp1').material('mat1').propertyGroup('def').set('poissonsratio', '0.4');
model.component('comp1').material('mat1').propertyGroup('def').set('thermalexpansioncoefficient', {'0.025' '0' '0' '0' '0.025' '0' '0' '0' '0.025'});
model.component('comp1').material('mat2').propertyGroup('def').set('thermalconductivity', {'0.21' '0' '0' '0' '0.21' '0' '0' '0' '0.21'});
model.component('comp1').material('mat2').propertyGroup('def').set('density', '1780');
model.component('comp1').material('mat2').propertyGroup('def').set('heatcapacity', '4200');
model.component('comp1').material('mat2').propertyGroup('def').set('youngsmodulus', '2.7e9');
model.component('comp1').material('mat2').propertyGroup('def').set('poissonsratio', '0.4');
model.component('comp1').material('mat2').propertyGroup('def').set('thermalexpansioncoefficient', {'10e-7' '0' '0' '0' '10e-7' '0' '0' '0' '10e-7'});

model.component('comp1').physics('ht').feature('temp1').set('T0', 'StandardTemp+0');
model.component('comp1').physics('ht').feature('temp2').set('T0', 'StandardTemp+0');
model.component('comp1').physics('ht').feature('temp3').set('T0', 'StandardTemp+0.3');
model.component('comp1').physics('ht').feature('temp4').set('T0', 'StandardTemp+0.4');
model.component('comp1').physics('ht').feature('temp5').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp6').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp7').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp8').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp9').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp10').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp11').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp12').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp13').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp14').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp15').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp16').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp17').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp18').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp19').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp20').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp21').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp22').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp23').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp24').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp25').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp26').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp27').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp28').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp29').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp30').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp31').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp32').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp33').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp34').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp35').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp36').set('T0', 'StandardTemp+1');
model.component('comp1').physics('ht').feature('temp37').set('T0', '293.15[K]-0.5');
model.component('comp1').physics('ht').feature('temp38').set('T0', '293.15[K]+1');
model.component('comp1').physics('ht').feature('temp39').set('T0', '293.15[K]+1');
model.component('comp1').physics('ht').feature('temp40').set('T0', '293.15[K]-1');
model.component('comp1').physics('ht').feature('temp41').set('T0', '293.15[K]+1');
model.component('comp1').physics('ht').feature('temp43').set('T0', '293.15[K]-1');
model.component('comp1').physics('ht').feature('temp45').set('T0', '293.15[K]+1');
model.component('comp1').physics('ht').feature('temp49').set('T0', '293.15[K]+1');
model.component('comp1').physics('ht').feature('temp51').set('T0', '293.15[K]+1');
model.component('comp1').physics('ht').feature('temp52').set('T0', '293.15[K]+1');
model.component('comp1').physics('ht').feature('temp53').set('T0', '293.15[K]-1');
model.component('comp1').physics('ht').feature('temp55').set('T0', '293.15[K]-1');
model.component('comp1').physics('ht').feature('temp56').set('T0', '293.15[K]-1');
model.component('comp1').physics('ht').feature('temp57').set('T0', '293.15[K]-1');
model.component('comp1').physics('ht').feature('temp58').set('T0', '293.15[K]-1');
model.component('comp1').physics('ht').feature('temp67').set('T0', '293.15[K]-1');
model.component('comp1').physics('ht').feature('temp68').set('T0', '293.15[K]-1');
model.component('comp1').physics('ht').feature('temp70').set('T0', '293.15[K]+1');
model.component('comp1').physics('ht').feature('temp72').set('T0', '293.15[K]-1');
model.component('comp1').physics('ht').feature('temp73').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp74').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp75').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp76').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp77').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp78').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp79').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp80').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp81').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp82').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp83').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp84').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp85').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp86').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp87').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp88').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp89').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp90').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp91').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp92').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp93').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp94').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp95').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp96').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp97').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp98').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp99').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp100').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp101').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp102').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp103').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp104').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp105').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp106').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp107').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp108').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp109').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp110').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp111').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp112').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp113').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp114').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp115').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp116').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp117').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp118').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp119').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp120').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp121').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp122').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp123').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp124').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp125').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp126').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp127').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp128').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp129').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp130').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp131').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp132').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp133').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp134').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp135').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp136').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp137').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp138').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp139').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp140').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp141').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp142').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp143').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp144').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp145').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp146').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp147').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp148').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp149').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp150').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp151').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp152').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp153').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp154').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp155').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp156').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp157').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp158').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp159').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp160').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp161').set('T0', 'StandardTemp');
model.component('comp1').physics('ht').feature('temp162').set('T0', 'StandardTemp');

model.study.create('std1');
model.study('std1').create('stat', 'Stationary');

model.sol.create('sol1');
model.sol('sol1').study('std1');
model.sol('sol1').attach('std1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('se1', 'Segregated');
model.sol('sol1').feature('s1').create('i1', 'Iterative');
model.sol('sol1').feature('s1').create('d1', 'Direct');
model.sol('sol1').feature('s1').create('i2', 'Iterative');
model.sol('sol1').feature('s1').create('d2', 'Direct');
model.sol('sol1').feature('s1').create('i3', 'Iterative');
model.sol('sol1').feature('s1').feature('se1').create('ss1', 'SegregatedStep');
model.sol('sol1').feature('s1').feature('se1').create('ss2', 'SegregatedStep');
model.sol('sol1').feature('s1').feature('se1').create('ll1', 'LowerLimit');
model.sol('sol1').feature('s1').feature('se1').feature.remove('ssDef');
model.sol('sol1').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol1').feature('s1').feature('i2').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i2').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i2').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i3').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i3').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i3').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i3').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol1').feature('s1').feature.remove('fcDef');

model.result.create('pg1', 'PlotGroup3D');
model.result.create('pg2', 'PlotGroup3D');
model.result.create('pg4', 'PlotGroup3D');
model.result('pg1').create('surf1', 'Surface');
model.result('pg2').create('iso1', 'Isosurface');
model.result('pg4').create('surf1', 'Surface');
model.result('pg4').feature('surf1').set('data', 'dset1');
model.result('pg4').feature('surf1').create('def1', 'Deform');

model.sol('sol1').attach('std1');
model.sol('sol1').feature('s1').feature('aDef').set('cachepattern', true);
model.sol('sol1').feature('s1').feature('se1').set('segtermonres', false);
model.sol('sol1').feature('s1').feature('se1').feature('ss1').label('Heat transfer T');
model.sol('sol1').feature('s1').feature('se1').feature('ss1').set('segvar', {'comp1_T'});
model.sol('sol1').feature('s1').feature('se1').feature('ss1').set('linsolver', 'i1');
model.sol('sol1').feature('s1').feature('se1').feature('ss1').set('subjtech', 'minimal');
model.sol('sol1').feature('s1').feature('se1').feature('ss2').set('segvar', {'comp1_u'});
model.sol('sol1').feature('s1').feature('se1').feature('ss2').set('linsolver', 'd1');
model.sol('sol1').feature('s1').feature('se1').feature('ll1').set('lowerlimit', 'comp1.T 0');
model.sol('sol1').feature('s1').feature('i1').label('Geometric Multigrid ht (te1)');
model.sol('sol1').feature('s1').feature('i1').set('rhob', 20);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('s1').feature('d1').label('Suggested Direct Solver solid (te1)');
model.sol('sol1').feature('s1').feature('i2').label('Suggested Iterative Solver solid (te1)');
model.sol('sol1').feature('s1').feature('i2').set('nlinnormuse', true);
model.sol('sol1').feature('s1').feature('i2').feature('mg1').feature('pr').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('i2').feature('mg1').feature('po').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('d2').label('PARDISO ht (te1)');
model.sol('sol1').feature('s1').feature('d2').set('linsolver', 'pardiso');
model.sol('sol1').feature('s1').feature('d2').set('pivotperturb', 1.0E-13);
model.sol('sol1').feature('s1').feature('i3').label('Algebraic Multigrid ht (te1)');
model.sol('sol1').feature('s1').feature('i3').feature('mg1').set('prefun', 'saamg');
model.sol('sol1').feature('s1').feature('i3').feature('mg1').set('usesmooth', false);
model.sol('sol1').feature('s1').feature('i3').feature('mg1').feature('pr').feature('so1').set('relax', 0.9);
model.sol('sol1').feature('s1').feature('i3').feature('mg1').feature('po').feature('so1').set('relax', 0.9);
model.sol('sol1').feature('s1').feature('i3').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').runAll;

model.result('pg1').label('Temperature (ht)');
model.result('pg1').feature('surf1').set('const', {'solid.refpntx' '0' 'Reference point for moment computation, x coordinate'; 'solid.refpnty' '0' 'Reference point for moment computation, y coordinate'; 'solid.refpntz' '0' 'Reference point for moment computation, z coordinate'});
model.result('pg1').feature('surf1').set('colortable', 'ThermalLight');
model.result('pg1').feature('surf1').set('resolution', 'normal');
model.result('pg2').label('Isothermal Contours (ht)');
model.result('pg2').feature('iso1').label('Isosurface');
model.result('pg2').feature('iso1').set('const', {'solid.refpntx' '0' 'Reference point for moment computation, x coordinate'; 'solid.refpnty' '0' 'Reference point for moment computation, y coordinate'; 'solid.refpntz' '0' 'Reference point for moment computation, z coordinate'});
model.result('pg2').feature('iso1').set('number', 10);
model.result('pg2').feature('iso1').set('colortable', 'ThermalLight');
model.result('pg2').feature('iso1').set('resolution', 'normal');
model.result('pg4').feature('surf1').set('expr', 'w');
model.result('pg4').feature('surf1').set('unit', 'mm');
model.result('pg4').feature('surf1').set('descr', 'Displacement field, Z component');
model.result('pg4').feature('surf1').set('const', {'solid.refpntx' '0' 'Reference point for moment computation, x coordinate'; 'solid.refpnty' '0' 'Reference point for moment computation, y coordinate'; 'solid.refpntz' '0' 'Reference point for moment computation, z coordinate'});
model.result('pg4').feature('surf1').set('resolution', 'normal');
model.result('pg4').feature('surf1').feature('def1').set('scaleactive', true);


for i = 1:m-n+1
    model.component('comp1').physics('ht').feature('temp1').set('T0', Temp1(i));
    model.component('comp1').physics('ht').feature('temp2').set('T0', Temp2(i));
    model.component('comp1').physics('ht').feature('temp3').set('T0', Temp3(i));
    model.component('comp1').physics('ht').feature('temp4').set('T0', Temp4(i));
    model.component('comp1').physics('ht').feature('temp5').set('T0', Temp5(i));
    model.component('comp1').physics('ht').feature('temp6').set('T0', Temp6(i));
    model.component('comp1').physics('ht').feature('temp7').set('T0', Temp7(i));
    model.component('comp1').physics('ht').feature('temp8').set('T0', Temp8(i));
    model.component('comp1').physics('ht').feature('temp9').set('T0', Temp9(i));
    model.component('comp1').physics('ht').feature('temp10').set('T0', Temp10(i));
    model.component('comp1').physics('ht').feature('temp11').set('T0', Temp11(i));
    model.component('comp1').physics('ht').feature('temp12').set('T0', Temp12(i));
    model.component('comp1').physics('ht').feature('temp13').set('T0', Temp13(i));
    model.component('comp1').physics('ht').feature('temp14').set('T0', Temp14(i));
    model.component('comp1').physics('ht').feature('temp15').set('T0', Temp15(i));
    model.component('comp1').physics('ht').feature('temp16').set('T0', Temp16(i));
    model.component('comp1').physics('ht').feature('temp17').set('T0', Temp17(i));
    model.component('comp1').physics('ht').feature('temp18').set('T0', Temp18(i));
    model.component('comp1').physics('ht').feature('temp19').set('T0', Temp19(i));
    model.component('comp1').physics('ht').feature('temp20').set('T0', Temp20(i));
    model.component('comp1').physics('ht').feature('temp21').set('T0', Temp21(i));
    model.component('comp1').physics('ht').feature('temp22').set('T0', Temp22(i));
    model.component('comp1').physics('ht').feature('temp23').set('T0', Temp23(i));
    model.component('comp1').physics('ht').feature('temp24').set('T0', Temp24(i));
    model.component('comp1').physics('ht').feature('temp25').set('T0', Temp25(i));
    model.component('comp1').physics('ht').feature('temp26').set('T0', Temp26(i));
    model.component('comp1').physics('ht').feature('temp27').set('T0', Temp27(i));
    model.component('comp1').physics('ht').feature('temp28').set('T0', Temp28(i));
    model.component('comp1').physics('ht').feature('temp29').set('T0', Temp29(i));
    model.component('comp1').physics('ht').feature('temp30').set('T0', Temp30(i));
    model.component('comp1').physics('ht').feature('temp31').set('T0', Temp31(i));
    model.component('comp1').physics('ht').feature('temp32').set('T0', Temp32(i));
    model.component('comp1').physics('ht').feature('temp33').set('T0', Temp33(i));
    model.component('comp1').physics('ht').feature('temp34').set('T0', Temp34(i));
    model.component('comp1').physics('ht').feature('temp35').set('T0', Temp35(i));
    model.component('comp1').physics('ht').feature('temp36').set('T0', Temp36(i));
    model.component('comp1').physics('ht').feature('temp37').set('T0', Temp37(i));
    model.component('comp1').physics('ht').feature('temp38').set('T0', Temp38(i));
    model.component('comp1').physics('ht').feature('temp39').set('T0', Temp39(i));
    model.component('comp1').physics('ht').feature('temp40').set('T0', Temp40(i));
    model.component('comp1').physics('ht').feature('temp41').set('T0', Temp41(i));
    model.component('comp1').physics('ht').feature('temp42').set('T0', Temp42(i));
    model.component('comp1').physics('ht').feature('temp43').set('T0', Temp43(i));
    model.component('comp1').physics('ht').feature('temp44').set('T0', Temp44(i));
    model.component('comp1').physics('ht').feature('temp45').set('T0', Temp45(i));
    model.component('comp1').physics('ht').feature('temp46').set('T0', Temp46(i));
    model.component('comp1').physics('ht').feature('temp47').set('T0', Temp47(i));
    model.component('comp1').physics('ht').feature('temp48').set('T0', Temp48(i));
    model.component('comp1').physics('ht').feature('temp49').set('T0', Temp49(i));
    model.component('comp1').physics('ht').feature('temp50').set('T0', Temp50(i));
    model.component('comp1').physics('ht').feature('temp51').set('T0', Temp51(i));
    model.component('comp1').physics('ht').feature('temp52').set('T0', Temp52(i));
    model.component('comp1').physics('ht').feature('temp53').set('T0', Temp53(i));
    model.component('comp1').physics('ht').feature('temp54').set('T0', Temp54(i));
    model.component('comp1').physics('ht').feature('temp55').set('T0', Temp55(i));
    model.component('comp1').physics('ht').feature('temp56').set('T0', Temp56(i));
    model.component('comp1').physics('ht').feature('temp57').set('T0', Temp57(i));
    model.component('comp1').physics('ht').feature('temp58').set('T0', Temp58(i));
    model.component('comp1').physics('ht').feature('temp59').set('T0', Temp59(i));
    model.component('comp1').physics('ht').feature('temp60').set('T0', Temp60(i));
    model.component('comp1').physics('ht').feature('temp61').set('T0', Temp61(i));
    model.component('comp1').physics('ht').feature('temp62').set('T0', Temp62(i));
    model.component('comp1').physics('ht').feature('temp63').set('T0', Temp63(i));
    model.component('comp1').physics('ht').feature('temp64').set('T0', Temp64(i));
    model.component('comp1').physics('ht').feature('temp65').set('T0', Temp65(i));
    model.component('comp1').physics('ht').feature('temp66').set('T0', Temp66(i));
    model.component('comp1').physics('ht').feature('temp67').set('T0', Temp67(i));
    model.component('comp1').physics('ht').feature('temp68').set('T0', Temp68(i));
    model.component('comp1').physics('ht').feature('temp69').set('T0', Temp69(i));
    model.component('comp1').physics('ht').feature('temp70').set('T0', Temp70(i));
    model.component('comp1').physics('ht').feature('temp71').set('T0', Temp71(i));
    model.component('comp1').physics('ht').feature('temp72').set('T0', Temp72(i));
    model.component('comp1').physics('ht').feature('temp73').set('T0', Temp73(i));
    model.component('comp1').physics('ht').feature('temp74').set('T0', Temp74(i));
    model.component('comp1').physics('ht').feature('temp75').set('T0', Temp75(i));
    model.component('comp1').physics('ht').feature('temp76').set('T0', Temp76(i));
    model.component('comp1').physics('ht').feature('temp77').set('T0', Temp77(i));
    model.component('comp1').physics('ht').feature('temp78').set('T0', Temp78(i));
    model.component('comp1').physics('ht').feature('temp79').set('T0', Temp79(i));
    model.component('comp1').physics('ht').feature('temp80').set('T0', Temp80(i));
    model.component('comp1').physics('ht').feature('temp81').set('T0', Temp81(i));
    model.component('comp1').physics('ht').feature('temp82').set('T0', Temp82(i));
    model.component('comp1').physics('ht').feature('temp83').set('T0', Temp83(i));
    model.component('comp1').physics('ht').feature('temp84').set('T0', Temp84(i));
    model.component('comp1').physics('ht').feature('temp85').set('T0', Temp85(i));
    model.component('comp1').physics('ht').feature('temp86').set('T0', Temp86(i));
    model.component('comp1').physics('ht').feature('temp87').set('T0', Temp87(i));
    model.component('comp1').physics('ht').feature('temp88').set('T0', Temp88(i));
    model.component('comp1').physics('ht').feature('temp89').set('T0', Temp89(i));
    model.component('comp1').physics('ht').feature('temp90').set('T0', Temp90(i));
    model.component('comp1').physics('ht').feature('temp91').set('T0', Temp91(i));
    model.component('comp1').physics('ht').feature('temp92').set('T0', Temp92(i));
    model.component('comp1').physics('ht').feature('temp93').set('T0', Temp93(i));
    model.component('comp1').physics('ht').feature('temp94').set('T0', Temp94(i));
    model.component('comp1').physics('ht').feature('temp95').set('T0', Temp95(i));
    model.component('comp1').physics('ht').feature('temp96').set('T0', Temp96(i));
    model.component('comp1').physics('ht').feature('temp97').set('T0', Temp97(i));
    model.component('comp1').physics('ht').feature('temp98').set('T0', Temp98(i));
    model.component('comp1').physics('ht').feature('temp99').set('T0', Temp99(i));
    model.component('comp1').physics('ht').feature('temp100').set('T0', Temp100(i));
    model.component('comp1').physics('ht').feature('temp101').set('T0', Temp101(i));
    model.component('comp1').physics('ht').feature('temp102').set('T0', Temp102(i));
    model.component('comp1').physics('ht').feature('temp103').set('T0', Temp103(i));
    model.component('comp1').physics('ht').feature('temp104').set('T0', Temp104(i));
    model.component('comp1').physics('ht').feature('temp105').set('T0', Temp105(i));
    model.component('comp1').physics('ht').feature('temp106').set('T0', Temp106(i));
    model.component('comp1').physics('ht').feature('temp107').set('T0', Temp107(i));
    model.component('comp1').physics('ht').feature('temp108').set('T0', Temp108(i));
    model.component('comp1').physics('ht').feature('temp109').set('T0', Temp109(i));
    model.component('comp1').physics('ht').feature('temp110').set('T0', Temp110(i));
    model.component('comp1').physics('ht').feature('temp111').set('T0', Temp111(i));
    model.component('comp1').physics('ht').feature('temp112').set('T0', Temp112(i));
    model.component('comp1').physics('ht').feature('temp113').set('T0', Temp113(i));
    model.component('comp1').physics('ht').feature('temp114').set('T0', Temp114(i));
    model.component('comp1').physics('ht').feature('temp115').set('T0', Temp115(i));
    model.component('comp1').physics('ht').feature('temp116').set('T0', Temp116(i));
    model.component('comp1').physics('ht').feature('temp117').set('T0', Temp117(i));
    model.component('comp1').physics('ht').feature('temp118').set('T0', Temp118(i));
    model.component('comp1').physics('ht').feature('temp119').set('T0', Temp119(i));
    model.component('comp1').physics('ht').feature('temp120').set('T0', Temp120(i));
    model.component('comp1').physics('ht').feature('temp121').set('T0', Temp121(i));
    model.component('comp1').physics('ht').feature('temp122').set('T0', Temp122(i));
    model.component('comp1').physics('ht').feature('temp123').set('T0', Temp123(i));
    model.component('comp1').physics('ht').feature('temp124').set('T0', Temp124(i));
    model.component('comp1').physics('ht').feature('temp125').set('T0', Temp125(i));
    model.component('comp1').physics('ht').feature('temp126').set('T0', Temp126(i));
    model.component('comp1').physics('ht').feature('temp127').set('T0', Temp127(i));
    model.component('comp1').physics('ht').feature('temp128').set('T0', Temp128(i));
    model.component('comp1').physics('ht').feature('temp129').set('T0', Temp129(i));
    model.component('comp1').physics('ht').feature('temp130').set('T0', Temp130(i));
    model.component('comp1').physics('ht').feature('temp131').set('T0', Temp131(i));
    model.component('comp1').physics('ht').feature('temp132').set('T0', Temp132(i));
    model.component('comp1').physics('ht').feature('temp133').set('T0', Temp133(i));
    model.component('comp1').physics('ht').feature('temp134').set('T0', Temp134(i));
    model.component('comp1').physics('ht').feature('temp135').set('T0', Temp135(i));
    model.component('comp1').physics('ht').feature('temp136').set('T0', Temp136(i));
    model.component('comp1').physics('ht').feature('temp137').set('T0', Temp137(i));
    model.component('comp1').physics('ht').feature('temp138').set('T0', Temp138(i));
    model.component('comp1').physics('ht').feature('temp139').set('T0', Temp139(i));
    model.component('comp1').physics('ht').feature('temp140').set('T0', Temp140(i));
    model.component('comp1').physics('ht').feature('temp141').set('T0', Temp141(i));
    model.component('comp1').physics('ht').feature('temp142').set('T0', Temp142(i));
    model.component('comp1').physics('ht').feature('temp143').set('T0', Temp143(i));
    model.component('comp1').physics('ht').feature('temp144').set('T0', Temp144(i));
    model.component('comp1').physics('ht').feature('temp145').set('T0', Temp145(i));
    model.component('comp1').physics('ht').feature('temp146').set('T0', Temp146(i));
    model.component('comp1').physics('ht').feature('temp147').set('T0', Temp147(i));
    model.component('comp1').physics('ht').feature('temp148').set('T0', Temp148(i));
    model.component('comp1').physics('ht').feature('temp149').set('T0', Temp149(i));
    model.component('comp1').physics('ht').feature('temp150').set('T0', Temp150(i));
    model.component('comp1').physics('ht').feature('temp151').set('T0', Temp151(i));
    model.component('comp1').physics('ht').feature('temp152').set('T0', Temp152(i));
    model.component('comp1').physics('ht').feature('temp153').set('T0', Temp153(i));
    model.component('comp1').physics('ht').feature('temp154').set('T0', Temp154(i));
    model.component('comp1').physics('ht').feature('temp155').set('T0', Temp155(i));
    model.component('comp1').physics('ht').feature('temp156').set('T0', Temp156(i));
    model.component('comp1').physics('ht').feature('temp157').set('T0', Temp157(i));
    model.component('comp1').physics('ht').feature('temp158').set('T0', Temp158(i));
    model.component('comp1').physics('ht').feature('temp159').set('T0', Temp159(i));
    model.component('comp1').physics('ht').feature('temp160').set('T0', Temp160(i));
    model.component('comp1').physics('ht').feature('temp161').set('T0', Temp161(i));
    model.component('comp1').physics('ht').feature('temp162').set('T0', Temp162(i));

    Animation_image = ['img',num2str(i)];
    Animation_data = ['data',num2str(i)];
    model.result.export.create(Animation_image, 'Image3D');
    model.result.export.create(Animation_data, 'Data');
    model.result.export(Animation_image).set('plotgroup', 'pg4');
    fname_fig = ['D:\White_paper\python\figure_9x9\',num2str(i+n-1),'.png'];
    model.result.export(Animation_image).set('pngfilename', fname_fig);
    model.result.export(Animation_image).set('printunit', 'mm');
    model.result.export(Animation_image).set('webunit', 'px');
    model.result.export(Animation_image).set('printheight', '90');
    model.result.export(Animation_image).set('webheight', '960');
    model.result.export(Animation_image).set('printwidth', '120');
    model.result.export(Animation_image).set('webwidth', '1280');
    model.result.export(Animation_image).set('printlockratio', 'off');
    model.result.export(Animation_image).set('weblockratio', 'off');
    model.result.export(Animation_image).set('printresolution', '300');
    model.result.export(Animation_image).set('webresolution', '200');
    model.result.export(Animation_image).set('size', 'manualweb');
    model.result.export(Animation_image).set('antialias', 'on');
    model.result.export(Animation_image).set('zoomextents', 'off');
    model.result.export(Animation_image).set('title', 'on');
    model.result.export(Animation_image).set('legend', 'on');
    model.result.export(Animation_image).set('logo', 'on');
    model.result.export(Animation_image).set('options', 'on');
    model.result.export(Animation_image).set('fontsize', '9');
    model.result.export(Animation_image).set('customcolor', [1 1 1]);
    model.result.export(Animation_image).set('background', 'color');
    model.result.export(Animation_image).set('axisorientation', 'on');
    model.result.export(Animation_image).set('grid', 'on');
    model.result.export(Animation_image).set('qualitylevel', '92');
    model.result.export(Animation_image).set('qualityactive', 'off');
    model.result.export(Animation_image).set('imagetype', 'png');
    model.result.export(Animation_data).set('expr', {'w'});
    model.result.export(Animation_data).set('unit', {'mm'});
    model.result.export(Animation_data).set('descr', {'Displacement field, Z component'});
    model.result.export(Animation_data).set('const', {'solid.refpntx' '0' 'Reference point for moment computation, x coordinate'; 'solid.refpnty' '0' 'Reference point for moment computation, y coordinate'; 'solid.refpntz' '0' 'Reference point for moment computation, z coordinate'});
    fname_data=['D:\White_paper\python\Comsol_data_9x9\',num2str(i+n-1),'.csv'];
    model.result.export(Animation_data).set('filename', fname_data);
    model.result.export(Animation_data).set('location', 'regulargrid');
    model.result.export(Animation_data).set('regulargridx3', 20);
    model.result.export(Animation_data).set('regulargridy3', 20);
    model.result.export(Animation_data).set('regulargridz3', 1);
    model.study('std1').run;
    model.result.export(Animation_image).run;
    model.result.export(Animation_data).run;
end

